=== michalkovy/ferda/ferda/src/Modules/Core/Boxes/boxesLocalization.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Tomas Kuchar (Ru-Board) -->
<!--W3C Schema generated by XMLSpy v2005 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ferda.is-a-geek.net" targetNamespace="http://ferda.is-a-geek.net" elementFormDefault="qualified">
	<xs:element name="BoxLocalization">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Identifier">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Label"/>
				<xs:element ref="Hint"/>
				<xs:element name="Categories">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Category" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="DynamicHelpItems" minOccurs="0"/>
				<xs:element name="Actions" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Action" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Name"/>
										<xs:element ref="Label"/>
										<xs:element ref="Hint"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Sockets" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Socket" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Name"/>
										<xs:element ref="Label"/>
										<xs:element ref="Hint"/>
										<xs:element name="SelectOptions" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="SelectOption" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PropertyCategories" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PropertyCategory" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Name"/>
										<xs:element ref="Label"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ModulesAskingForCreationSeq" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ModulesAskingForCreation" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Name"/>
										<xs:element ref="Label"/>
										<xs:element ref="Hint"/>
										<xs:element ref="DynamicHelpItems" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="HelpFiles" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HelpFile" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Identifier">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="Label"/>
										<xs:element name="Version" type="xs:integer"/>
										<xs:element name="Path">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Phrases" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Phrase" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PhraseIdentifier">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PhraseText">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Category">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Label"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Hint">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ShortLabel">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Label">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SelectOption">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Label"/>
				<xs:element ref="ShortLabel" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BoxesLocalization">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="BoxLocalization" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DynamicHelpItem">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Identifer">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Label"/>
				<xs:element name="Url">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DynamicHelpItems">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DynamicHelpItem" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Url">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="url://anywhere"/>
				<xs:enumeration value="url://something.somewhere"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== michalkovy/ferda/ferda/src/Modules/BoxModulesServices/boxesLocalization.en-US.xml
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSpy v2006 sp1 U (http://www.altova.com) by Xx Xx (Xx Xx) --><BoxesLocalization xmlns="http://ferda.is-a-geek.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ferda.is-a-geek.net../Core/Boxes/boxesLocalization.xsd">	<BoxLocalization>		<Identifier>DataPreparation.DataSource.Database</Identifier>		<Label>Database</Label>		<Hint>Defines data source and its parameters</Hint>		<Categories>			<Category>				<Name>DataPreparation.DataSource</Name>				<Label>Data preparation.Data source</Label>			</Category>		</Categories>		<Actions>			<Action>				<Name>ReloadRequest</Name>				<Label>Reload Request</Label>				<Hint>This will reload the structure and statisticts information about the database, data tables and columns.</Hint>			</Action>		</Actions>		<Sockets>			<Socket>				<Name>ProviderInvariantName</Name>				<Label>Provider invariant name</Label>				<Hint>The invariant name of data provider.</Hint>			</Socket>			<Socket>				<Name>ConnectionString</Name>				<Label>Connection string</Label>				<Hint>Provider specific connection string for data source that defines database to be analyzed.</Hint>			</Socket>			<Socket>				<Name>LastReloadRequest</Name>				<Label>Last reload request</Label>				<Hint>Last user request to the structure and statisticts information about the database, data tables and columns.</Hint>			</Socket>			<Socket>				<Name>AcceptableDataTableTypes</Name>				<Label>Acceptable data table types</Label>				<Hint>Database contains of many types of data tables. This property allows you to filter data tables by selected acceptable types.</Hint>				<SelectOptions>					<SelectOption>						<Name>ALIAS</Name>						<Label>ALIAS</Label>					</SelectOption>					<SelectOption>						<Name>TABLE</Name>						<Label>TABLE</Label>					</SelectOption>					<SelectOption>						<Name>SYNONYM</Name>						<Label>SYNONYM</Label>					</SelectOption>					<SelectOption>						<Name>SYSTEM TABLE</Name>						<Label>SYSTEM TABLE</Label>					</SelectOption>					<SelectOption>						<Name>VIEW</Name>						<Label>VIEW</Label>					</SelectOption>					<SelectOption>						<Name>GLOBAL TEMPORARY</Name>						<Label>GLOBAL TEMPORARY</Label>					</SelectOption>					<SelectOption>						<Name>LOCAL TEMPORARY</Name>						<Label>LOCAL TEMPORARY</Label>					</SelectOption>					<SelectOption>						<Name>EXTERNAL TABLE</Name>						<Label>EXTERNAL TABLE</Label>					</SelectOption>					<SelectOption>						<Name>SYSTEM VIEW</Name>						<Label>SYSTEM VIEW</Label>					</SelectOption>				</SelectOptions>			</Socket>			<Socket>				<Name>ConnectionTimeout</Name>				<Label>Connection timeout</Label>				<Hint>Time to wait while establishing a connection before terminating the attempt.</Hint>			</Socket>			<Socket>				<Name>DatabaseName</Name>				<Label>Database`s name</Label>				<Hint>The name of the database.</Hint>			</Socket>			<Socket>				<Name>DataSource</Name>				<Label>Data souce</Label>				<Hint>The server name or file name of the data source.</Hint>			</Socket>			<Socket>				<Name>Driver</Name>				<Label>Driver</Label>				<Hint>The name of the ODBC driver specified for the current connection.</Hint>			</Socket>			<Socket>				<Name>ServerVersion</Name>				<Label>Version of server</Label>				<Hint>The version of the server to which the client is connected.</Hint>			</Socket>		</Sockets>		<PropertyCategories>			<PropertyCategory>				<Name>ConnectionSetting</Name>				<Label>Connection setting</Label>			</PropertyCategory>			<PropertyCategory>				<Name>ConnectionInfo</Name>				<Label>Connection info</Label>			</PropertyCategory>		</PropertyCategories>		<ModulesAskingForCreationSeq>			<ModulesAskingForCreation>				<Name>DataMatrix</Name>				<Label>Data matrix @Name</Label>				<Hint>Creates box corresponding to the table @Name</Hint>			</ModulesAskingForCreation>			<ModulesAskingForCreation>				<Name>AllDataMatrixes</Name>				<Label>All data matrixes in DB</Label>				<Hint>Creates boxes for all data matrixes in this databse.</Hint>			</ModulesAskingForCreation>		</ModulesAskingForCreationSeq>	</BoxLocalization>	<BoxLocalization>		<Identifier>DataPreparation.DataSource.DataTable</Identifier>		<Label>Data table</Label>		<Hint>Defines data matrix and its parameters</Hint>		<Categories>			<Category>				<Name>DataPreparation.DataSource</Name>				<Label>Data preparation.Data source</Label>			</Category>		</Categories>		<Sockets>			<Socket>				<Name>Database</Name>				<Label>Database</Label>				<Hint>Defines data source for the data matrix.</Hint>			</Socket>			<Socket>				<Name>Name</Name>				<Label>Name</Label>				<Hint>Name of the table. The name will enclosed in aphostrophes in SQL query.</Hint>			</Socket>			<Socket>				<Name>Type</Name>				<Label>Type</Label>				<Hint>Type of data table.</Hint>			</Socket>			<Socket>				<Name>Remarks</Name>				<Label>Remarks</Label>				<Hint>Remarks.</Hint>			</Socket>			<Socket>				<Name>PrimaryKeyColumns</Name>				<Label>Primary key</Label>				<Hint>List of columns that define the primary key of the table. The value is either a value of one column or CSV (comma separated values). It will be not enclosed in apostrophes.</Hint>			</Socket>			<Socket>				<Name>RecordsCount</Name>				<Label>Records count</Label>				<Hint>Number of rows in the table (pre-computed field).</Hint>			</Socket>		</Sockets>		<PropertyCategories>			<PropertyCategory>				<Name>Schema</Name>				<Label>Schema</Label>			</PropertyCategory>			<PropertyCategory>				<Name>Statistics</Name>				<Label>Statistics</Label>			</PropertyCategory>		</PropertyCategories>		<ModulesAskingForCreationSeq>			<ModulesAskingForCreation>				<Name>DerivedColumn</Name>				<Label>Derived column</Label>				<Hint>Creates box of a new defived column</Hint>			</ModulesAskingForCreation>			<ModulesAskingForCreation>				<Name>Column</Name>				<Label>Column @Name</Label>				<Hint>Creates box corresponding to the column @Name</Hint>			</ModulesAskingForCreation>			<ModulesAskingForCreation>				<Name>AllColumns</Name>				<Label>All columns in data matrix</Label>				<Hint>Creates boxes for all columns inthis datamatrix.</Hint>			</ModulesAskingForCreation>		</ModulesAskingForCreationSeq>	</BoxLocalization>	<BoxLocalization>		<Identifier>DataPreparation.DataSource.Column</Identifier>		<Label>Column</Label>		<Hint>Defines column of the table and its parameters</Hint>		<Categories>			<Category>				<Name>DataPreparation.DataSource</Name>				<Label>Data preparation.Data source</Label>			</Category>		</Categories>		<Sockets>			<Socket>				<Name>DataTable</Name>				<Label>Data table</Label>				<Hint>Defines data matrix or Multi-column.</Hint>			</Socket>			<Socket>				<Name>SelectExpression</Name>				<Label>Select expression</Label>				<Hint>Name of column or SQL formula as select expression. The name of column will be enclosed by apostrophes in SQL queries, specified formul will not be enclosed in apostrophes in the SQL query.</Hint>			</Socket>			<Socket>				<Name>DataType</Name>				<Label>Data type</Label>				<Hint>Column data type.</Hint>				<SelectOptions>					<SelectOption>						<Name>UnknownType</Name>						<Label>Unknown</Label>					</SelectOption>					<SelectOption>						<Name>BooleanType</Name>						<Label>Boolean</Label>					</SelectOption>					<SelectOption>						<Name>DateTimeType</Name>						<Label>Date Time</Label>					</SelectOption>					<SelectOption>						<Name>TimeType</Name>						<Label>Time</Label>					</SelectOption>					<SelectOption>						<Name>ShortIntegerType</Name>						<Label>Short Integer</Label>					</SelectOption>					<SelectOption>						<Name>IntegerType</Name>						<Label>Integer</Label>					</SelectOption>					<SelectOption>						<Name>LongIntegerType</Name>						<Label>Long Integer</Label>					</SelectOption>					<SelectOption>						<Name>UnsignedShortIntegerType</Name>						<Label>Unsigned Short Integer</Label>					</SelectOption>					<SelectOption>						<Name>UnsignedIntegerType</Name>						<Label>Unsigned Integer</Label>					</SelectOption>					<SelectOption>						<Name>UnsignedLongIntegerType</Name>						<Label>Unsigned Long Integer</Label>					</SelectOption>					<SelectOption>						<Name>FloatType</Name>						<Label>Float</Label>					</SelectOption>					<SelectOption>						<Name>DoubleType</Name>						<Label>Double</Label>					</SelectOption>					<SelectOption>						<Name>DecimalType</Name>						<Label>Decimal</Label>					</SelectOption>					<SelectOption>						<Name>StringType</Name>						<Label>String</Label>					</SelectOption>				</SelectOptions>			</Socket>			<Socket>				<Name>Cardinality</Name>				<Label>Cardinality</Label>				<Hint>You should specify the cardinality of the column values.</Hint>				<SelectOptions>					<SelectOption>						<Name>Nominal</Name>						<Label>Nominal</Label>					</SelectOption>					<SelectOption>						<Name>Ordinal</Name>						<Label>Ordinal</Label>					</SelectOption>					<SelectOption>						<Name>OrdinalCyclic</Name>						<Label>Ordinal Cyclic</Label>					</SelectOption>					<SelectOption>						<Name>Cardinal</Name>						<Label>Cardinal</Label>					</SelectOption>				</SelectOptions>			</Socket>			<Socket>				<Name>ValueMin</Name>				<Label>Minimum</Label>				<Hint>Minimal value in the column.</Hint>			</Socket>			<Socket>				<Name>ValueMax</Name>				<Label>Maximum</Label>				<Hint>Maximal value in the column.</Hint>			</Socket>			<Socket>				<Name>ValueAverage</Name>				<Label>Average</Label>				<Hint>Average value in the column.</Hint>			</Socket>			<Socket>				<Name>ValueVariability</Name>				<Label>Variability</Label>				<Hint>Variability of values in the column.</Hint>			</Socket>			<Socket>				<Name>Val
